spring:
  datasource:
    url: jdbc:h2:mem:matrix-campus;TIME ZONE=UTC
    username: test
    password: test
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    generate-ddl: true
    defer-datasource-initialization: true
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  jackson:
    time-zone: UTC
    #defer-datasource-initialization: true